import { createFileRoute } from "@tanstack/react-router";
import { Children, useState, type ReactNode } from "react";
import { ArrowUpRight, Baby, Brain, CalendarDays, CheckCircle2, ChevronDown, Clock3, HeartHandshake, Instagram, Leaf, MapPin, Menu, MessageCircle, Moon, Phone, ShieldCheck, Sparkles, UsersRound, X } from "lucide-react";
import logoAsset from "@/assets/logo-prosaude.png.asset.json";
import waIcon from "@/assets/wa-icon.png.asset.json";

export const Route = createFileRoute("/")({ component: Index, head:()=>({meta:[{title:"Essência do Cuidar | Clínica de Psicologia"},{name:"description",content:"Clínica de psicologia com atendimento acolhedor para adultos, crianças, idosos, casais e famílias, além de acompanhamento nutricional."}]}) });
const wa="https://wa.me/557597018423?text=Ol%C3%A1!%20Quero%20agendar%20um%20atendimento%20na%20Ess%C3%AAncia%20do%20Cuidar.";
const mapUrl="https://www.google.com/maps/search/?api=1&query=Essencia+do+Cuidar+Clinica+de+Psicologia";
const nav:[string,string][]=[["Início","#inicio"],["A Clínica","#clinica"],["Especialidades","#especialidades"],["Nossa Equipe","#equipe"],["Para quem é","#publico"],["Dúvidas","#duvidas"],["Contato","#contato"]];
const hero="https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1800&q=90";
const clinic="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=90";
const images=["https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=900&q=90","https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=900&q=90","https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=900&q=90","https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=900&q=90"];
const specialties=[[Brain,"Psicologia para adultos","Acolhimento para ansiedade, estresse, autoestima, relacionamentos e diferentes fases da vida."],[Baby,"Psicologia infantil","Um espaço seguro e acolhedor para crianças, respeitando seu tempo, emoções e desenvolvimento."],[UsersRound,"Casais e famílias","Escuta e acompanhamento para melhorar o diálogo, fortalecer vínculos e atravessar momentos difíceis."],[Moon,"Psicologia para idosos","Cuidado emocional em fases de mudanças, luto, solidão, adaptação e novos projetos de vida."],[HeartHandshake,"Acolhimento psicológico","Um espaço de escuta sem julgamentos para compreender o que você está vivendo e encontrar novos caminhos."],[Leaf,"Nutrição","Acompanhamento nutricional com olhar individualizado para uma relação mais leve e consciente com a alimentação."] ] as const;
const reviews=[["Mariana Silva","Encontrei um espaço muito acolhedor. Fui ouvida com respeito e saí de cada encontro mais tranquila e consciente."],["Carlos Mendes","O atendimento transmite muita confiança. Desde o primeiro contato, me senti respeitado e acolhido."],["Ana Paula","Minha filha se adaptou muito bem. O cuidado e a delicadeza no atendimento fizeram toda diferença para nossa família."],["Fernanda Alves","Um ambiente bonito, tranquilo e profissionais muito atenciosos. Foi uma experiência muito positiva."],["Juliana Costa","O acompanhamento me ajudou a olhar para mim com mais carinho e entender melhor minhas emoções."] ] as const;
const faqs=["Como funciona a primeira consulta?","O atendimento é para crianças e adultos?","A clínica atende casais e famílias?","Como funciona o acompanhamento nutricional?","Como posso agendar meu atendimento?","Onde fica a clínica?"];
function Button({children="Agendar atendimento",href=wa,light=false}:{children?:ReactNode;href?:string;light?:boolean}){return <a className={`ps-btn ${light?"ps-btn-light":""}`} href={href} target={href.startsWith("http")?"_blank":undefined} rel={href.startsWith("http")?"noreferrer":undefined}><MessageCircle size={17}/>{children}<ArrowUpRight size={15}/></a>}
function Title({eyebrow,title,sub}:{eyebrow:string;title:string;sub:string}){return <div className="ps-section-title"><span className="section-eyebrow"><Sparkles size={14}/>{eyebrow}</span><h2>{title}</h2><p>{sub}</p></div>}
function Logo({small=false}:{small?:boolean}){return <div className={`ps-logo ${small?"small":""}`}><div className="logo-mark"><HeartHandshake size={small?22:28}/></div><div><strong>Essência do Cuidar</strong><small>CLÍNICA DE PSICOLOGIA</small></div></div>}
function Marquee({children,label,duration=42}:{children:ReactNode;label:string;duration?:number}){const items=Children.toArray(children);return <div className="marquee" aria-label={label}><div className="marquee-track" style={{["--marquee-duration" as string]:`${duration}s`}}>{items}{items.map((x,i)=><div key={i} style={{display:"contents"}} aria-hidden="true">{x}</div>)}</div></div>}
function Index(){const[menu,setMenu]=useState(false);const[faq,setFaq]=useState<number|null>(0);return <div className="ps-page"><header className="ps-header"><a href="#inicio"><Logo small/></a><nav>{nav.map(([x,h])=><a href={h} key={x}>{x}</a>)}</nav><a className="header-wa" href={wa} target="_blank" rel="noreferrer"><Phone size={17}/><span>Agende pelo WhatsApp<br/><b>Fale com nossa equipe</b></span></a><button className="menu-btn" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>{menu&&<div className="mobile-menu">{nav.map(([x,h])=><a href={h} key={x} onClick={()=>setMenu(false)}>{x}</a>)}<Button/></div>}<main>
<section id="inicio" className="ps-hero"><div className="hero-bg"><img src={hero} alt="Ambiente acolhedor para cuidado emocional"/></div><div className="hero-copy"><span className="mini-label">ESSÊNCIA DO CUIDAR · CLÍNICA DE PSICOLOGIA</span><h1>Um espaço para <em>cuidar de você</em> por inteiro.</h1><p>Psicologia e nutrição em um ambiente acolhedor, humano e seguro para adultos, crianças, idosos, casais e famílias.</p><div className="hero-actions"><Button>Agendar minha consulta</Button><Button light href="#especialidades">Conheça nossos atendimentos</Button></div><div className="hero-trust"><span><CheckCircle2/>Escuta sem julgamentos</span><span><CheckCircle2/>Atendimento individualizado</span><span><CheckCircle2/>Cuidado em todas as fases</span></div></div></section>
<section className="ps-intro"><div className="intro-card"><div className="intro-icon"><HeartHandshake/></div><div><b>Você não precisa passar por tudo sozinho.</b><p>Buscar ajuda também é uma forma de se cuidar.</p></div></div><div className="intro-card"><div className="intro-icon"><ShieldCheck/></div><div><b>Um espaço seguro para ser você.</b><p>Respeito, privacidade e acolhimento em cada encontro.</p></div></div><div className="intro-card"><div className="intro-icon"><Leaf/></div><div><b>Cuidado que olha para o todo.</b><p>Saúde emocional e hábitos mais saudáveis caminham juntos.</p></div></div></section>
<section id="especialidades" className="ps-section"><Title eyebrow="Nossos atendimentos" title="Cuidado psicológico para diferentes momentos da vida" sub="Cada pessoa tem uma história. Nosso trabalho começa com uma escuta atenta e um atendimento construído de forma individualizada."/><Marquee label="Especialidades da clínica" duration={38}>{specialties.map(([Icon,name,text],i)=><article className="specialty-card" key={name}><div className="specialty-visual"><img src={images[i%images.length]} alt={name} loading="lazy"/><span>{String(i+1).padStart(2,"0")}</span><div className="card-icon"><Icon/></div></div><div className="specialty-body"><h3>{name}</h3><p>{text}</p><a href={wa} target="_blank" rel="noreferrer">Quero saber mais <ArrowUpRight size={15}/></a></div></article>)}</Marquee><div className="section-cta"><Button>Conversar com a equipe</Button></div></section>
<section className="ps-services"><Title eyebrow="Como podemos ajudar" title="Um cuidado pensado para você" sub="Atendimento próximo, respeitoso e personalizado para acolher diferentes necessidades."/><div className="service-grid"><article className="service-card"><div className="service-icon"><Brain/></div><h3>Psicoterapia</h3><p>Um espaço para compreender emoções, pensamentos, comportamentos e relações.</p></article><article className="service-card"><div className="service-icon"><UsersRound/></div><h3>Casais e famílias</h3><p>Para quem deseja construir diálogos mais saudáveis e fortalecer vínculos.</p></article><article className="service-card"><div className="service-icon"><Leaf/></div><h3>Nutrição</h3><p>Orientação para uma relação mais consciente, equilibrada e possível com a alimentação.</p></article></div></section>
<section id="equipe" className="team-section"><Title eyebrow="Nossa equipe" title="Profissionais preparados para acolher sua história" sub="Uma equipe multidisciplinar, com psicólogos e nutricionista, trabalhando com atenção às necessidades de cada pessoa."/><div className="team-grid">{[["Psicologia","Cuidado emocional e escuta individualizada"],["Psicologia","Acompanhamento psicológico personalizado"],["Psicologia","Acolhimento para diferentes fases da vida"],["Nutrição","Cuidado alimentar individualizado"]].map(([role,text],i)=><article className="team-card" key={i}><img src={images[i]} alt={role} loading="lazy"/><div className="team-card-body"><div className="team-role">{role}</div><h3>{i===3?"Nutricionista":"Psicólogo(a)"}</h3><p>{text}</p><a href={wa} target="_blank" rel="noreferrer">Agendar atendimento <ArrowUpRight size={14}/></a></div></article>)}</div></section>
<section id="publico" className="audience"><div className="audience-grid"><div className="audience-copy"><span className="section-eyebrow">Para quem é</span><h2>Existe um espaço para cada história.</h2><p>Nosso atendimento foi pensado para acompanhar pessoas em diferentes fases e contextos, sempre respeitando sua individualidade.</p><Button light>Encontrar meu atendimento</Button></div><div className="audience-list"><div className="audience-item"><Baby/><b>Crianças e adolescentes</b></div><div className="audience-item"><Brain/><b>Adultos</b></div><div className="audience-item"><HeartHandshake/><b>Casais</b></div><div className="audience-item"><UsersRound/><b>Famílias</b></div><div className="audience-item"><Moon/><b>Idosos</b></div><div className="audience-item"><Leaf/><b>Nutrição</b></div></div></div></section>
<section id="clinica" className="about"><div className="about-grid"><div className="about-photo"><img src={clinic} alt="Ambiente da clínica" loading="lazy"/></div><div className="about-copy"><span className="section-eyebrow">A Essência do Cuidar</span><h2>Um ambiente tranquilo para cuidar do que realmente importa.</h2><p>A Essência do Cuidar nasce com o propósito de oferecer um atendimento humano, acolhedor e individualizado. Aqui, cada pessoa é recebida com respeito à sua história, ao seu momento e às suas necessidades.</p><div className="values"><div className="value"><HeartHandshake/><b>Acolhimento</b><small>Escuta com respeito e empatia.</small></div><div className="value"><ShieldCheck/><b>Segurança</b><small>Privacidade e cuidado.</small></div><div className="value"><Leaf/><b>Individualidade</b><small>Um plano para cada história.</small></div></div><Button>Conhecer a clínica</Button></div></div></section>
<section className="ps-banner"><div><span>UM PASSO DE CADA VEZ</span><h2>Seu cuidado começa quando você decide se priorizar.</h2></div><Button light>Quero conversar</Button></section>
<section className="reviews"><Title eyebrow="O que nossos pacientes dizem" title="Experiências que acolhem" sub="O vínculo e a confiança fazem parte do processo de cuidado."/><Marquee label="Avaliações" duration={34}>{reviews.map(([name,text])=><article className="review-card" key={name}><div className="review-top"><div className="avatar">{name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><b>{name}</b><div className="stars">★★★★★</div></div></div><p>“{text}”</p><div className="review-foot"><CheckCircle2/> Atendimento Essência do Cuidar</div></article>)}</Marquee></section>
<section id="duvidas" className="faq"><div className="faq-grid"><div className="faq-intro"><span className="section-eyebrow">Dúvidas frequentes</span><h2>Antes de começar, talvez você queira saber...</h2><p>Se sua dúvida não estiver aqui, nossa equipe pode orientar você pelo WhatsApp.</p><Button>Tirar minha dúvida</Button></div><div className="faq-list">{faqs.map((q,i)=><div className="faq-item" key={q}><button onClick={()=>setFaq(faq===i?null:i)} aria-expanded={faq===i}><span>0{i+1}</span><b>{q}</b><ChevronDown className={faq===i?"rotate":""}/></button>{faq===i&&<p>Entre em contato com nossa equipe pelo WhatsApp. Vamos explicar como funciona o atendimento e orientar você sobre o melhor caminho.</p>}</div>)}</div></div></section>
<section id="contato" className="contact"><div className="contact-grid"><div className="contact-copy"><span className="section-eyebrow">Fale conosco</span><Logo/><h2>Vamos conversar sobre o seu momento?</h2><p>Agende seu atendimento ou tire suas dúvidas com nossa equipe.</p><Button>Agendar pelo WhatsApp</Button><div className="contact-details"><span><MessageCircle/> WhatsApp para agendamento</span><span><MapPin/> Localização da clínica</span><span><Clock3/> Atendimento com hora marcada</span></div></div><div className="contact-map"><iframe title="Localização da clínica" src="https://www.google.com/maps?q=Essencia%20do%20Cuidar%20Clinica%20de%20Psicologia&output=embed" loading="lazy"/></div></div></section>
</main><footer className="footer"><div className="footer-grid"><div><Logo/><p>Um espaço de acolhimento, escuta e cuidado para todas as fases da vida.</p></div><div><h3>Links rápidos</h3>{nav.slice(0,6).map(([x,h])=><a href={h} key={x}>{x}</a>)}</div><div><h3>Atendimentos</h3><a href="#especialidades">Psicologia</a><a href="#especialidades">Infantil</a><a href="#especialidades">Casais e famílias</a><a href="#especialidades">Nutrição</a></div><div><h3>Contato</h3><a href={wa} target="_blank" rel="noreferrer"><Phone/> WhatsApp</a><a href={mapUrl} target="_blank" rel="noreferrer"><MapPin/> Como chegar</a><a href="https://instagram.com" target="_blank" rel="noreferrer"><Instagram/> Instagram</a></div></div><div className="footer-bottom"><span>© 2026 Essência do Cuidar. Todos os direitos reservados.</span><span>Privacidade · Termos de uso</span></div></footer><a className="floating-wa" href={wa} target="_blank" rel="noreferrer" aria-label="WhatsApp"><img src={waIcon.url} alt="WhatsApp"/></a></div>}
